In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

## Creare & Read

#### 1D Array

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

### 2D Array

In [9]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape #(row, column)

(2, 3)

### 3D Array

In [16]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [18]:
arr3.ndim

3

In [19]:
arr3.shape #(how much 2d array, rows, columns)

(3, 2, 3)

### Create Random Array

In [20]:
randomArr = np.random.rand(3, 2, 3)

In [21]:
randomArr

array([[[0.4348854 , 0.3793945 , 0.89320752],
        [0.05907574, 0.47977968, 0.27839113]],

       [[0.35907989, 0.56038268, 0.40560337],
        [0.29565148, 0.69748317, 0.18143718]],

       [[0.74224433, 0.52701968, 0.15006884],
        [0.39142545, 0.11681653, 0.54984519]]])

In [23]:
randomArr.dtype

dtype('float64')

In [25]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
zeroes.ndim

3

In [27]:
full = np.full((3, 2, 3),8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [29]:
arr3[0][0]

array([1, 4, 5])

### Update & Delete

In [30]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [31]:
a1

array([[[0.08971199, 0.8500016 ],
        [0.5259961 , 0.67595317],
        [0.84090038, 0.50602154]],

       [[0.48947341, 0.91447135],
        [0.24897823, 0.23626406],
        [0.65852157, 0.11755862]]])

### Mathematical Operations

In [32]:
np.add(a1,a2)

array([[[0.35329575, 1.16566631],
        [1.01734702, 0.97140224],
        [1.75988268, 1.31494138]],

       [[0.97891113, 1.06614921],
        [1.01574552, 1.19191781],
        [1.58907101, 0.79039275]]])

In [33]:
np.subtract(a1,a2)

array([[[-1.73871764e-01,  5.34336893e-01],
        [ 3.46451704e-02,  3.80504100e-01],
        [-7.80819189e-02, -3.02898305e-01]],

       [[ 3.56930297e-05,  7.62793482e-01],
        [-5.17789047e-01, -7.19389698e-01],
        [-2.72027880e-01, -5.55275507e-01]]])

In [34]:
np.divide(a1,a2)

array([[[0.34035479, 2.69273561],
        [1.07051003, 2.2878839 ],
        [0.91503436, 0.62555214]],

       [[1.00007293, 6.02903625],
        [0.3247116 , 0.24722768],
        [0.70766961, 0.17472155]]])

In [35]:
np.multiply(a1,a2)

array([[[0.02364662, 0.26831551],
        [0.25844867, 0.19970973],
        [0.77277257, 0.40933086]],

       [[0.23956675, 0.13870506],
        [0.19090836, 0.22578663],
        [0.61278688, 0.07909745]]])

### Statical operations

In [37]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [38]:
sqrt

np.float64(5.0)

In [39]:
abs

np.int64(2)

In [40]:
power

np.int64(256)

In [41]:
log

np.float64(3.2188758248682006)

In [42]:
mins

np.float64(0.08971199425797027)

In [43]:
maxs

np.float64(0.9556537563331805)

### Update

In [44]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [45]:
arr3[0, 0, 2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [46]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [47]:
# Reshape
arr3.shape

(3, 2, 3)

In [48]:
arr3_reshape = arr3.reshape((2, 3, 3))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [49]:
arr3.shape

(3, 2, 3)

In [50]:
arr3_reshape.shape

(2, 3, 3)

### Appending & Inserting

In [52]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
appd = np.append(zeroes, new_array, axis =0) # axis 0=row, axis 1 =column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
# INSERT

In [56]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [58]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])